### ISSUE TITLE
Wrong keyboard mapping

### ISSUE THREAD

**Issue by Fabus1184** [ingemaradahl/remote-input#4]
I'm using german keymap (QWERTZ) and regardless of the keymap settings at client or server the keymap is always wrong, z and y are switched and I cant write most special characters even not when pressing the key that would correspond to the character in american layout. Also the super key is not working, but that **might** be an issue with ksuperkey idk.

**Comment by ingemaradahl** [comment]
Yeah, I use dvorak which becomes interesting when I use this tool to forward my local X11 input to another computer which also runs a X11 server with the same keymap: When I press <kbd>S</kbd> the dvorak layout maps this to the <kbd>O</kbd> key which is picked up by the forward-input application and sent to the receiving end, which in turn is pressed again as <kbd>O</kbd> on the virtual keyboard. This is translated to <kbd>R</kbd> by the dvorak keymap. So If I press <kbd>O</kbd> I get <kbd>R</kbd> which is super confusing :slightly_smiling_face:. Essentially you get a on-the-fly substitution cipher.

However I've used this as a feature, since I get dvorak when I forward my input to machines with a standard US QWERTY keyboard layout. Quirky but it works. But also a bit crazy.

I guess it makes sense to be able to choose if you want to forward the X11 keyboard presses or the "actual" key presses. A sensible default would probably be to forward the same key as you pressed on the keyboard regardless of what your X11 mapping is..
